package com.entity;

// Generated 2016-4-16 15:43:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "projectdatabase")
public class Project implements java.io.Serializable
{

	private Integer projectId;
	private String project;
	private Character type;
	private Character area;
	private Character contractStage;
	private Character projectStage;
	private Double contractAmount;
	private Double completedAmount;
	private Double receivedAmount;
	private Double contractBalance;
	private Date projectTime;
	private Team team;
	private Set<Subproject> subprojects = new HashSet<Subproject>(0);

	public Project()
	{
	}

	public Project(String project, Character type, Character area,
                   Character contractStage, Character projectStage,
                   Double contractAmount, Double completedAmount,
                   Double receivedAmount, Double contractBalance, Date projectTime,
                   Set<Subproject> subprojects)
	{
		this.project = project;
		this.type = type;
		this.area = area;
		this.contractStage = contractStage;
		this.projectStage = projectStage;
		this.contractAmount = contractAmount;
		this.completedAmount = completedAmount;
		this.receivedAmount = receivedAmount;
		this.contractBalance = contractBalance;
		this.projectTime = projectTime;
		this.subprojects = subprojects;
	}
	public Project(String project, Character type, Character area,
                   Character contractStage, Character projectStage,
                   Double contractAmount, Double completedAmount,
                   Double receivedAmount, Double contractBalance, Date projectTime,
                   Set<Subproject> subprojects, Team projectTeam)
	{
		this.project = project;
		this.type = type;
		this.area = area;
		this.contractStage = contractStage;
		this.projectStage = projectStage;
		this.contractAmount = contractAmount;
		this.completedAmount = completedAmount;
		this.receivedAmount = receivedAmount;
		this.contractBalance = contractBalance;
		this.projectTime = projectTime;
		this.subprojects = subprojects;
		this.team = projectTeam;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectId", unique = true, nullable = false)
	public Integer getProjectId()
	{
		return this.projectId;
	}

	public void setProjectId(Integer projectId)
	{
		this.projectId = projectId;
	}

	@Column(name = "project", length = 200)
	public String getProject()
	{
		return this.project;
	}

	public void setProject(String project)
	{
		this.project = project;
	}

	@Column(name = "type", length = 1)
	public Character getType()
	{
		return this.type;
	}

	public void setType(Character type)
	{
		this.type = type;
	}

	@Column(name = "area", length = 1)
	public Character getArea()
	{
		return this.area;
	}

	public void setArea(Character area)
	{
		this.area = area;
	}

	@Column(name = "contract_stage", length = 1)
	public Character getContractStage()
	{
		return this.contractStage;
	}

	public void setContractStage(Character contractStage)
	{
		this.contractStage = contractStage;
	}

	@Column(name = "project_stage", length = 1)
	public Character getProjectStage()
	{
		return this.projectStage;
	}

	public void setProjectStage(Character projectStage)
	{
		this.projectStage = projectStage;
	}

	@Column(name = "contract_amount", precision = 22, scale = 0)
	public Double getContractAmount()
	{
		return this.contractAmount;
	}

	public void setContractAmount(Double contractAmount)
	{
		this.contractAmount = contractAmount;
	}

	@Column(name = "completed_amount", precision = 22, scale = 0)
	public Double getCompletedAmount()
	{
		return this.completedAmount;
	}

	public void setCompletedAmount(Double completedAmount)
	{
		this.completedAmount = completedAmount;
	}

	@Column(name = "received_amount", precision = 22, scale = 0)
	public Double getReceivedAmount()
	{
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount)
	{
		this.receivedAmount = receivedAmount;
	}

	@Column(name = "contract_balance", precision = 22, scale = 0)
	public Double getContractBalance()
	{
		return this.contractBalance;
	}

	public void setContractBalance(Double contractBalance)
	{
		this.contractBalance = contractBalance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "project_time", length = 10)
	public Date getProjectTime()
	{
		return this.projectTime;
	}

	public void setProjectTime(Date projectTime)
	{
		this.projectTime = projectTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Subproject> getSubprojects()
	{
		return this.subprojects;
	}

	public void setSubprojects(Set<Subproject> subprojects)
	{
		this.subprojects = subprojects;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "team")
	public Team getTeam(){return this.team;}
	public void setTeam(Team t){this.team = t;}
}
