package com.entity;

// Generated 2016-4-16 15:43:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * ProjectMember generated by mzhejiayu
 */
@Entity
@Table(
        name = "teamUser", catalog = "projectdatabase",
        uniqueConstraints= @UniqueConstraint(columnNames = {"role", "openId" ,"teamId"})
)
public class TeamUser implements java.io.Serializable
{

    private Integer teamUserId;
    private Team team;
    private User user;
    private Integer role;

    public TeamUser()
    {
    }

    public TeamUser(Team team, User user, Integer role)
    {
        this.team = team;
        this.user = user;
        this.role = role;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "teamUserId", unique = true, nullable = false)
    public Integer getTeamUserId()
    {
        return this.teamUserId;
    }

    public void setTeamUserId(Integer teamUserId)
    {
        this.teamUserId = teamUserId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "openId")
    public User getUser()
    {
        return this.user;
    }

    public void setUser(User user)
    {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "teamId")
    public Team getTeam()
    {
        return this.team;
    }

    public void setTeam(Team team)
    {
        this.team = team;
    }



    @Column(name = "role", length = 1)
    public Integer getRole()
    {
        return this.role;
    }

    public void setRole(Integer role)
    {
        this.role = role;
    }

}
