package com.entity;

// Generated 2016-4-16 15:43:05 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team", catalog = "projectdatabase")
public class Team implements java.io.Serializable
{

    private Integer teamId;
    private String teamName;
    private String relatedTitle;
    private Set<TeamUser> teamUsers = new HashSet<TeamUser>(0);
    private Set<Project> projects = new HashSet<>(0);
    public Team()
    {
    }

    public Team(String teamName,String relatedTitle, Set<TeamUser> teamUsers )
    {
        this.teamName = teamName;
        this.relatedTitle = relatedTitle;
        this.teamUsers = teamUsers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "teamId", unique = true, nullable = false)
    public Integer getTeamId()
    {
        return this.teamId;
    }

    public void setTeamId(Integer teamId)
    {
        this.teamId = teamId;
    }


    @Column(name = "teamName", length = 45)
    public String getTeamName()
    {
        return this.teamName;
    }

    public void setTeamName(String team)
    {
        this.teamName = team;
    }

    @Column(name = "relatedTitle", length = 200)
    public String getRelatedTitle()
    {
        if(this.relatedTitle==null||this.relatedTitle.equals("")){
            this.relatedTitle = "合同备案进度|付款进度|分配进度|计划进度安排|一周内出图、回文安排|一周内会议组织|外部设计条件是否充分|内部带落实事宜|总结交流活动";
        }
        return this.relatedTitle;
    }

    public void setRelatedTitle(String relatedTitle)
    {
        this.relatedTitle=relatedTitle;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "team")
    public Set<TeamUser> getTeamUsers()
    {
        return this.teamUsers;
    }

    public void setTeamUsers(Set<TeamUser> teamUsers)
    {
        this.teamUsers = teamUsers;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name="team")
    public Set<Project> getProjects(){return this.projects;}
    public void setProjects(Set<Project> p ){this.projects = p;}


}
